// <auto-generated />
using System;
using Contacts.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Contacts.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180908140750_ContactsSeedData")]
    partial class ContactsSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Contacts.API.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Name");

                    b.Property<string>("Surname");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new { ContactId = 1, Address = "8106 Linda Ave., Schenectady, NY 12302", DateOfBirth = new DateTime(1964, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), Name = "Keanu", Surname = "Reeves" },
                        new { ContactId = 2, Address = "7201 N. Roehampton Ave., Easton, PA 18042", DateOfBirth = new DateTime(1971, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), Name = "Elon", Surname = "Musk" },
                        new { ContactId = 3, Address = "Erlenweg 57, 3027 Bern, Switzerland", DateOfBirth = new DateTime(1981, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), Name = "Roger", Surname = "Federer" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
