// <auto-generated />
using System;
using Contacts.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Contacts.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180908165326_UniqueIndexes")]
    partial class UniqueIndexes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Contacts.API.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressNumber")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("postcode")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.HasKey("AddressId");

                    b.HasAlternateKey("Street", "AddressNumber", "postcode", "City", "Country");

                    b.HasIndex("AddressId")
                        .IsUnique()
                        .HasName("AddressIdIDX");

                    b.ToTable("Address");

                    b.HasData(
                        new { AddressId = 1, AddressNumber = "8106", City = "Schenectady", Country = "New York, US", Street = "Linda Ave.", postcode = "12302" },
                        new { AddressId = 2, AddressNumber = "7201", City = "Easton", Country = "Pennsylvania, US", Street = "N. Roehampton Ave.", postcode = "18042" },
                        new { AddressId = 3, AddressNumber = "57", City = "Bern", Country = "Switzerland", Street = "Erlenweg", postcode = "3027" }
                    );
                });

            modelBuilder.Entity("Contacts.API.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddressId");

                    b.Property<DateTime?>("DateOfBirth");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("ContactId");

                    b.HasIndex("AddressId")
                        .HasName("AddressIdIDX");

                    b.HasIndex("ContactId")
                        .IsUnique()
                        .HasName("ContactIdIDX");

                    b.HasIndex("Name")
                        .HasName("ContactNameIDX");

                    b.HasIndex("Surname")
                        .HasName("ContactSurnameIDX");

                    b.ToTable("Contacts");

                    b.HasData(
                        new { ContactId = 1, AddressId = 1, DateOfBirth = new DateTime(1964, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), Name = "Keanu", Surname = "Reeves" },
                        new { ContactId = 2, AddressId = 2, DateOfBirth = new DateTime(1971, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), Name = "Elon", Surname = "Musk" },
                        new { ContactId = 3, AddressId = 3, DateOfBirth = new DateTime(1981, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), Name = "Roger", Surname = "Federer" }
                    );
                });

            modelBuilder.Entity("Contacts.API.Models.ContactData", b =>
                {
                    b.Property<int>("ContactDataID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactDataStatus")
                        .IsRequired()
                        .HasMaxLength(1);

                    b.Property<string>("ContactDataType")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("ContactDataValue")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("ContactId");

                    b.HasKey("ContactDataID");

                    b.HasAlternateKey("ContactId", "ContactDataType", "ContactDataValue");

                    b.HasIndex("ContactDataID")
                        .IsUnique()
                        .HasName("ContactDataIdIDX");

                    b.HasIndex("ContactId")
                        .HasName("ContactIdIDX");

                    b.ToTable("ContactData");

                    b.HasData(
                        new { ContactDataID = 1, ContactDataStatus = "M", ContactDataType = "PHONE", ContactDataValue = "090/0000-000", ContactId = 1 },
                        new { ContactDataID = 2, ContactDataStatus = "Y", ContactDataType = "PHONE", ContactDataValue = "090/0000-001", ContactId = 1 },
                        new { ContactDataID = 3, ContactDataStatus = "Y", ContactDataType = "MAIL", ContactDataValue = "keanu.reeves@mail.com", ContactId = 1 },
                        new { ContactDataID = 4, ContactDataStatus = "Y", ContactDataType = "PHONE", ContactDataValue = "090/0000-100", ContactId = 2 },
                        new { ContactDataID = 5, ContactDataStatus = "M", ContactDataType = "MAIL", ContactDataValue = "elon.musk@mail.com", ContactId = 2 },
                        new { ContactDataID = 6, ContactDataStatus = "Y", ContactDataType = "MAIL", ContactDataValue = "elon.musk@anothermail.com", ContactId = 2 },
                        new { ContactDataID = 7, ContactDataStatus = "Y", ContactDataType = "PHONE", ContactDataValue = "090/0000-200", ContactId = 3 }
                    );
                });

            modelBuilder.Entity("Contacts.API.Models.ContactTag", b =>
                {
                    b.Property<int>("ContactTagId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContactId");

                    b.Property<string>("ContactTagName")
                        .IsRequired();

                    b.HasKey("ContactTagId");

                    b.HasAlternateKey("ContactId", "ContactTagName");

                    b.HasIndex("ContactId")
                        .HasName("ContactIdIDX");

                    b.HasIndex("ContactTagId")
                        .IsUnique()
                        .HasName("ContactTagIdIDX");

                    b.HasIndex("ContactTagName")
                        .HasName("ContactTagNameIDX");

                    b.ToTable("ContactTag");

                    b.HasData(
                        new { ContactTagId = 1, ContactId = 1, ContactTagName = "friend" },
                        new { ContactTagId = 2, ContactId = 2, ContactTagName = "roleModel" },
                        new { ContactTagId = 3, ContactId = 2, ContactTagName = "colleague" },
                        new { ContactTagId = 4, ContactId = 3, ContactTagName = "family" }
                    );
                });

            modelBuilder.Entity("Contacts.API.Models.Contact", b =>
                {
                    b.HasOne("Contacts.API.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Contacts.API.Models.ContactData", b =>
                {
                    b.HasOne("Contacts.API.Models.Contact", "Contact")
                        .WithMany("ContactData")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Contacts.API.Models.ContactTag", b =>
                {
                    b.HasOne("Contacts.API.Models.Contact", "Contact")
                        .WithMany("ContactTags")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
